export const FETCH_REVIEW_SUCCESS = 'entities/FETCH_REVIEW_SUCCESS';
export const FETCH_FRIENDSHIPS_SUCCESS = 'entities/FETCH_FRIENDSHIPS_SUCCESS';
export const UPLOAD_PICTURES = 'entities/UPLOAD_PICTURES';
