export const FETCH_FRIENDSHIPS_SUCCESS = 'friends/FETCH_FRIENDSHIPS_SUCCESS';
export const FETCH_REQUESTS_SUCCESS = 'friends/FETCH_REQUESTS_SUCCESS';
export const SEND_NOTIFICATION = 'friends/SEND_NOTIFICATION';
export const SEND_REQUEST = 'friends/SEND_REQUEST';
export const SEEN_REQUESTS = 'friends/SEEN_REQUESTS';
