export const FETCH_FRIENDSHIPS_SUCCESS = 'friends/FETCH_FRIENDSHIPS_SUCCESS';
export const FETCH_REQUESTS_SUCCESS = 'friends/FETCH_REQUESTS_SUCCESS';
export const SEND_FRIEND_REQUEST_NOTIFICATION = 'friends/SEND_FRIEND_REQUEST_NOTIFICATION';
