export const UPDATE_PROFILE = 'users/UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'users/UPDATE_PROFILE_SUCCESS';
export const FETCH_FRIENDSHIPS_SUCCESS = 'users/FETCH_FRIENDSHIPS_SUCCESS';
export const LOGOUT = 'users/LOGOUT';
